name: testovyi
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"

dependencies:
  auto_route: ^5.0.4
  # async: ^2.9.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  dropdown_button2: ^1.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  # flutter_html: ^3.0.0-alpha.6
  flutter_html: ^3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  freezed_annotation:
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  l: ^4.0.1
  package_info_plus: ^4.0.2
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  stream_bloc: ^0.5.3
  syncfusion_flutter_charts: ^22.1.38
  web_socket_channel: ^2.4.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.5
  # bloc_test: ^9.0.3
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  lint: ^2.1.2

flutter_gen:
  output: lib/src/core/gen
  integrations:
    flutter_svg: true
    # flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/icons/